{% set version = "2.6.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-treemapify
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/treemapify_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/treemapify/treemapify_{{ version }}.tar.gz
  sha256: 32fa713cae4fc2c00353fd3fb57a386553d9d3973c55a619d32aa21011eb07c3

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli >=3.6.1
    - r-ggfittext >=0.5.0
    - r-ggplot2 >=3.5
    - r-svglite
  run:
    - r-base
    - r-cli >=3.6.1
    - r-ggfittext >=0.5.0
    - r-ggplot2 >=3.5
    - r-svglite

test:
  commands:
    - $R -e "library('treemapify')"           # [not win]
    - "\"%R%\" -e \"library('treemapify')\""  # [win]

about:
  home: https://github.com/wilkox/treemapify
  license: GPL-3.0-or-later
  summary: Provides 'ggplot2' geoms for drawing treemaps.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
