{% set version = "2.5.6" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-treemapify
  version: {{ version|replace("-", "_") }}

source:
  fn: treemapify_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/treemapify_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/treemapify/treemapify_{{ version }}.tar.gz
  sha256: 0fa766f3afaaed889fb62f272ed2b4bb82a8a172a40f0779795fdc2c08f225f0

build:
  noarch: generic
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-ggfittext >=0.5.0
    - r-ggplot2 >=2.2.1
  run:
    - r-base
    - r-ggfittext >=0.5.0
    - r-ggplot2 >=2.2.1

test:
  commands:
    - $R -e "library('treemapify')"           # [not win]
    - "\"%R%\" -e \"library('treemapify')\""  # [win]

about:
  home: https://github.com/wilkox/treemapify
  license: GPL (>= 3)
  summary: Provides 'ggplot2' geoms for drawing treemaps.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
