appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: PVFE61UvwtXPTVtnmnxqLhl6kcu6gCQ++TDAuJJZO0Gn1jhx+dRPYpBjZ5w1ObDILBwS5v8+zQ6WYMy/pe8bylYep4+v2kpAWNWDtmhXeUDcdpH2INb22ozlTjBhmD8W42QS2UXjOWnuA3cYgDqyKfp0q2+sV9VRDrCjvIQaVEAUE1fa+j/XwLJJ2Qh8LzylBxKCsoB7i6UzrJA8OkS71J3Zwy/LhDGNrhGMDeKxK5k4C38Soua7149T/nhSWhUAGgsewxhCArcnssn+7FaU8tIPfue0Uj9rSu5HupuLrg7GV/JspJxw7sWd8Cp7XUrF6vQEVrGNuAauHlHaq9vY1sxYTQLk3k5NIq1saxLT7/WhXbRsEgP6qQPpRRMB8HhsPhMe2ZQOEgGSwOoETdtqWngFHH0eBiYkyQK24yG7DMe0uS7SVrQpUAJaeCiLzCjRk9Xx/meqqSD8ZZys5qOPfmhjsx10Vt24utANHAwteHyCzDkS+Z2A+1/BfJvYoMu4tF/FQg8a4k9DYc9eXqWynKoKXCO7jJz5XzT66YHK/asy3QtoUZjRj5Xq8KIP5cFd1ZagIjwdbLFKPmKfTILQxuhAf9sEtzmyogAN0qo1zQTNnPxyikb+FsPDxiYCrWXa0DncC8uPUN7MNWUiA4Ytny3zLwHRqPB4SNUoZtjJ6SI=
conda_forge_output_validation: true
